export { HomePage } from "./HomePage"
export { PlanesPage } from "./PlanesPage"
export { EspaciosPage } from "./EspaciosPage"
export { UbicacionPage } from "./UbicacionPage"
export { ContactoPage } from "./ContactoPage"
export { LoginPage } from "./LoginPage"
